port: 1337 # cause that's how we roll
markdown: maruku
authors: # author details
  andreasbovens:
    display_name: Andreas Bovens
    twitter: andreasbovens
    github: andreasbovens
  chrismills:
    display_name: Chris Mills
    twitter: chrisdavidmills
    github: chrisdavidmills
  shwetankdixit:
    display_name: Shwetank Dixit
    twitter: shwetank
    github: shwetank
  demonstro:
    display_name: Christian Magnus Sinding-Larsen
    icon:
    twitter:
    github:
exclude:
- 'node_modules'
- 'Gruntfile.js'
- 'package.json'
- 'README.md'
- '*.psd'
